# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/preferencesDialog.ui'
#
# Created: Sun Nov 30 11:27:17 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CanardPreferencesDialog(object):
    def setupUi(self, CanardPreferencesDialog):
        CanardPreferencesDialog.setObjectName(_fromUtf8("CanardPreferencesDialog"))
        CanardPreferencesDialog.resize(512, 375)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/preferences-system-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CanardPreferencesDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(CanardPreferencesDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = FingerTabWidget(CanardPreferencesDialog)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkForUpdates = QtGui.QCheckBox(self.tab_4)
        self.checkForUpdates.setEnabled(False)
        self.checkForUpdates.setObjectName(_fromUtf8("checkForUpdates"))
        self.horizontalLayout_2.addWidget(self.checkForUpdates)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.tab_4)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.spinBox = QtGui.QSpinBox(self.tab_4)
        self.spinBox.setMaximum(1000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 270, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Canard_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.defaultDisplayLanguage = QtGui.QComboBox(self.tab)
        self.defaultDisplayLanguage.setEditable(False)
        self.defaultDisplayLanguage.setObjectName(_fromUtf8("defaultDisplayLanguage"))
        self.horizontalLayout.addWidget(self.defaultDisplayLanguage)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.addDefaultNewLang = QtGui.QPushButton(self.tab)
        self.addDefaultNewLang.setObjectName(_fromUtf8("addDefaultNewLang"))
        self.gridLayout.addWidget(self.addDefaultNewLang, 3, 1, 1, 1)
        self.removeDefaultNewLang = QtGui.QPushButton(self.tab)
        self.removeDefaultNewLang.setObjectName(_fromUtf8("removeDefaultNewLang"))
        self.gridLayout.addWidget(self.removeDefaultNewLang, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.defaultNewLangs = QtGui.QListWidget(self.tab)
        self.defaultNewLangs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.defaultNewLangs.setObjectName(_fromUtf8("defaultNewLangs"))
        self.gridLayout.addWidget(self.defaultNewLangs, 1, 0, 5, 1)
        self.possibleDefaultNewLangs = QtGui.QListWidget(self.tab)
        self.possibleDefaultNewLangs.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.possibleDefaultNewLangs.setObjectName(_fromUtf8("possibleDefaultNewLangs"))
        self.gridLayout.addWidget(self.possibleDefaultNewLangs, 1, 2, 5, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/applications-development-translation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(CanardPreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CanardPreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CanardPreferencesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CanardPreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CanardPreferencesDialog)

    def retranslateUi(self, CanardPreferencesDialog):
        CanardPreferencesDialog.setWindowTitle(QtGui.QApplication.translate("CanardPreferencesDialog", "Canard Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.checkForUpdates.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "Check for updates on startup. (Coming soon)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "Check for updates now...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "Number of frames before disabling auto-updates", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("CanardPreferencesDialog", "Canard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("CanardPreferencesDialog", "This language will be selected when viewing an object.\n"
"If the object doesnt have this language the first available will be used instead", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "Default display language:", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultDisplayLanguage.setToolTip(QtGui.QApplication.translate("CanardPreferencesDialog", "This language will be selected when viewing an object.\n"
"If the object doesnt have this language the first available will be used instead", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "Interface Language:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("CanardPreferencesDialog", "Coming soon...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "Lanugages to add to all new objects", None, QtGui.QApplication.UnicodeUTF8))
        self.addDefaultNewLang.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "<- Add", None, QtGui.QApplication.UnicodeUTF8))
        self.removeDefaultNewLang.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "Remove ->", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "All Languages", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CanardPreferencesDialog", "When adding a new object, the languages on the left will always be selectable.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("CanardPreferencesDialog", "Languages", None, QtGui.QApplication.UnicodeUTF8))

from SQBLWidgets.FingerTabWidget import FingerTabWidget
import canard_rc
