# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/question.ui'
#
# Created: Sun Nov 30 11:27:15 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(586, 514)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_6 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.name = QtGui.QLineEdit(Form)
        self.name.setToolTip(_fromUtf8(""))
        self.name.setObjectName(_fromUtf8("name"))
        self.horizontalLayout_2.addWidget(self.name)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.questionTabs = QtGui.QTabWidget(Form)
        self.questionTabs.setTabPosition(QtGui.QTabWidget.North)
        self.questionTabs.setObjectName(_fromUtf8("questionTabs"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.targetPopulation = QtGui.QListWidget(self.tab_3)
        self.targetPopulation.setMaximumSize(QtCore.QSize(16777215, 65))
        self.targetPopulation.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.targetPopulation.setObjectName(_fromUtf8("targetPopulation"))
        self.gridLayout_4.addWidget(self.targetPopulation, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dataElementURI = QtGui.QLineEdit(self.groupBox)
        self.dataElementURI.setObjectName(_fromUtf8("dataElementURI"))
        self.gridLayout.addWidget(self.dataElementURI, 0, 1, 1, 1)
        self.openDataElementInBrowser = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openDataElementInBrowser.sizePolicy().hasHeightForWidth())
        self.openDataElementInBrowser.setSizePolicy(sizePolicy)
        self.openDataElementInBrowser.setMinimumSize(QtCore.QSize(125, 0))
        self.openDataElementInBrowser.setObjectName(_fromUtf8("openDataElementInBrowser"))
        self.gridLayout.addWidget(self.openDataElementInBrowser, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 2, 1)
        self.previewDataElementPage = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewDataElementPage.sizePolicy().hasHeightForWidth())
        self.previewDataElementPage.setSizePolicy(sizePolicy)
        self.previewDataElementPage.setMinimumSize(QtCore.QSize(125, 0))
        self.previewDataElementPage.setObjectName(_fromUtf8("previewDataElementPage"))
        self.gridLayout.addWidget(self.previewDataElementPage, 0, 2, 1, 1)
        self.dataElementPagePreview = QtWebKit.QWebView(self.groupBox)
        self.dataElementPagePreview.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataElementPagePreview.sizePolicy().hasHeightForWidth())
        self.dataElementPagePreview.setSizePolicy(sizePolicy)
        self.dataElementPagePreview.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.dataElementPagePreview.setObjectName(_fromUtf8("dataElementPagePreview"))
        self.gridLayout.addWidget(self.dataElementPagePreview, 2, 1, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 2)
        self.questionTabs.addTab(self.tab_3, _fromUtf8(""))
        self.textTab = QtGui.QWidget()
        self.textTab.setObjectName(_fromUtf8("textTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.textTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.questionTabs.addTab(self.textTab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.responseTabs = QtGui.QTabWidget(self.tab_2)
        self.responseTabs.setTabsClosable(True)
        self.responseTabs.setMovable(True)
        self.responseTabs.setObjectName(_fromUtf8("responseTabs"))
        self.gridLayout_2.addWidget(self.responseTabs, 3, 1, 1, 3)
        self.label_5 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        self.widget_2 = QtGui.QWidget(self.tab_2)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.canRefuse = QtGui.QRadioButton(self.widget_2)
        self.canRefuse.setChecked(True)
        self.canRefuse.setObjectName(_fromUtf8("canRefuse"))
        self.verticalLayout_4.addWidget(self.canRefuse)
        self.radioButton = QtGui.QRadioButton(self.widget_2)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_4.addWidget(self.radioButton)
        self.gridLayout_2.addWidget(self.widget_2, 1, 2, 1, 2)
        self.widget = QtGui.QWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.canDontKnow = QtGui.QRadioButton(self.widget)
        self.canDontKnow.setChecked(False)
        self.canDontKnow.setObjectName(_fromUtf8("canDontKnow"))
        self.verticalLayout_3.addWidget(self.canDontKnow)
        self.radioButton_3 = QtGui.QRadioButton(self.widget)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_3.addWidget(self.radioButton_3)
        self.gridLayout_2.addWidget(self.widget, 2, 2, 1, 2)
        self.questionTabs.addTab(self.tab_2, _fromUtf8(""))
        self.subQuestionsTab = QtGui.QWidget()
        self.subQuestionsTab.setObjectName(_fromUtf8("subQuestionsTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.subQuestionsTab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.questionTabs.addTab(self.subQuestionsTab, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.questionTabs)
        self.label.setBuddy(self.name)

        self.retranslateUi(Form)
        self.questionTabs.setCurrentIndex(0)
        self.responseTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.name, self.questionTabs)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Question Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.targetPopulation.setSortingEnabled(False)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Respondent universe:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Data Element", None, QtGui.QApplication.UnicodeUTF8))
        self.openDataElementInBrowser.setText(QtGui.QApplication.translate("Form", " Open in Browser... ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Uniform Resource Identifier (URI)", None, QtGui.QApplication.UnicodeUTF8))
        self.previewDataElementPage.setText(QtGui.QApplication.translate("Form", "Preview content", None, QtGui.QApplication.UnicodeUTF8))
        self.questionTabs.setTabText(self.questionTabs.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Concept", None, QtGui.QApplication.UnicodeUTF8))
        self.questionTabs.setTabText(self.questionTabs.indexOf(self.textTab), QtGui.QApplication.translate("Form", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Refusal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Don\'t know", None, QtGui.QApplication.UnicodeUTF8))
        self.canRefuse.setText(QtGui.QApplication.translate("Form", "Can Refuse", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Form", "Must answer", None, QtGui.QApplication.UnicodeUTF8))
        self.canDontKnow.setText(QtGui.QApplication.translate("Form", "Allowed", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("Form", "Not Allowed", None, QtGui.QApplication.UnicodeUTF8))
        self.questionTabs.setTabText(self.questionTabs.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Response", None, QtGui.QApplication.UnicodeUTF8))
        self.questionTabs.setTabText(self.questionTabs.indexOf(self.subQuestionsTab), QtGui.QApplication.translate("Form", "Subquestions", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
