# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/responseText.ui'
#
# Created: Sat Jul 25 11:37:51 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(378, 220)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hasDisplayHint = QtGui.QCheckBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hasDisplayHint.sizePolicy().hasHeightForWidth())
        self.hasDisplayHint.setSizePolicy(sizePolicy)
        self.hasDisplayHint.setMinimumSize(QtCore.QSize(90, 0))
        self.hasDisplayHint.setMaximumSize(QtCore.QSize(110, 16777215))
        self.hasDisplayHint.setObjectName(_fromUtf8("hasDisplayHint"))
        self.gridLayout.addWidget(self.hasDisplayHint, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.hasMinLength = QtGui.QCheckBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hasMinLength.sizePolicy().hasHeightForWidth())
        self.hasMinLength.setSizePolicy(sizePolicy)
        self.hasMinLength.setMinimumSize(QtCore.QSize(90, 0))
        self.hasMinLength.setMaximumSize(QtCore.QSize(110, 16777215))
        self.hasMinLength.setObjectName(_fromUtf8("hasMinLength"))
        self.gridLayout.addWidget(self.hasMinLength, 2, 0, 1, 1)
        self.hasMaxLength = QtGui.QCheckBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hasMaxLength.sizePolicy().hasHeightForWidth())
        self.hasMaxLength.setSizePolicy(sizePolicy)
        self.hasMaxLength.setMinimumSize(QtCore.QSize(90, 0))
        self.hasMaxLength.setMaximumSize(QtCore.QSize(110, 16777215))
        self.hasMaxLength.setObjectName(_fromUtf8("hasMaxLength"))
        self.gridLayout.addWidget(self.hasMaxLength, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(90, 0))
        self.label_3.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 4, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.languages = QtGui.QComboBox(Form)
        self.languages.setEditable(False)
        self.languages.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.languages.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.languages.setObjectName(_fromUtf8("languages"))
        self.horizontalLayout_3.addWidget(self.languages)
        self.addLanguage = QtGui.QPushButton(Form)
        self.addLanguage.setMaximumSize(QtCore.QSize(30, 16777215))
        self.addLanguage.setObjectName(_fromUtf8("addLanguage"))
        self.horizontalLayout_3.addWidget(self.addLanguage)
        self.removeLanguage = QtGui.QPushButton(Form)
        self.removeLanguage.setMaximumSize(QtCore.QSize(30, 16777215))
        self.removeLanguage.setObjectName(_fromUtf8("removeLanguage"))
        self.horizontalLayout_3.addWidget(self.removeLanguage)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 6)
        self.minLengthHint = QtGui.QLineEdit(Form)
        self.minLengthHint.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minLengthHint.sizePolicy().hasHeightForWidth())
        self.minLengthHint.setSizePolicy(sizePolicy)
        self.minLengthHint.setObjectName(_fromUtf8("minLengthHint"))
        self.gridLayout.addWidget(self.minLengthHint, 3, 1, 1, 4)
        self.displayHint = QtGui.QLineEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayHint.sizePolicy().hasHeightForWidth())
        self.displayHint.setSizePolicy(sizePolicy)
        self.displayHint.setObjectName(_fromUtf8("displayHint"))
        self.gridLayout.addWidget(self.displayHint, 1, 1, 1, 5)
        self.maxLengthHint = QtGui.QLineEdit(Form)
        self.maxLengthHint.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxLengthHint.sizePolicy().hasHeightForWidth())
        self.maxLengthHint.setSizePolicy(sizePolicy)
        self.maxLengthHint.setObjectName(_fromUtf8("maxLengthHint"))
        self.gridLayout.addWidget(self.maxLengthHint, 5, 1, 1, 5)
        self.minLengthValue = QtGui.QSpinBox(Form)
        self.minLengthValue.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minLengthValue.sizePolicy().hasHeightForWidth())
        self.minLengthValue.setSizePolicy(sizePolicy)
        self.minLengthValue.setMaximum(16777215)
        self.minLengthValue.setObjectName(_fromUtf8("minLengthValue"))
        self.gridLayout.addWidget(self.minLengthValue, 2, 1, 1, 1)
        self.maxLengthValue = QtGui.QSpinBox(Form)
        self.maxLengthValue.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxLengthValue.sizePolicy().hasHeightForWidth())
        self.maxLengthValue.setSizePolicy(sizePolicy)
        self.maxLengthValue.setMaximum(16777215)
        self.maxLengthValue.setObjectName(_fromUtf8("maxLengthValue"))
        self.gridLayout.addWidget(self.maxLengthValue, 4, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.hasMinLength, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.minLengthHint.setEnabled)
        QtCore.QObject.connect(self.hasMaxLength, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.maxLengthHint.setEnabled)
        QtCore.QObject.connect(self.hasMinLength, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.minLengthValue.setEnabled)
        QtCore.QObject.connect(self.hasMaxLength, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.maxLengthValue.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.displayHint, self.maxLengthHint)
        Form.setTabOrder(self.maxLengthHint, self.hasMaxLength)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.hasDisplayHint.setText(QtGui.QApplication.translate("Form", "Display Hint", None, QtGui.QApplication.UnicodeUTF8))
        self.hasMinLength.setText(QtGui.QApplication.translate("Form", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.hasMaxLength.setText(QtGui.QApplication.translate("Form", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Hint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Hint", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.addLanguage.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removeLanguage.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.minLengthHint.setPlaceholderText(QtGui.QApplication.translate("Form", "Shown if a respondents answer is too short.", None, QtGui.QApplication.UnicodeUTF8))
        self.displayHint.setPlaceholderText(QtGui.QApplication.translate("Form", "Optionally shown to assist with the response (like a placeholder like this)", None, QtGui.QApplication.UnicodeUTF8))
        self.maxLengthHint.setPlaceholderText(QtGui.QApplication.translate("Form", "Shown if a respondents answer is too long.", None, QtGui.QApplication.UnicodeUTF8))

