# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sqbl_main.ui'
#
# Created: Sat Jul 25 12:16:34 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(911, 613)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue,Helvetica,Arial,sans-serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(37)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Statement.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("* {\n"
"    font-family:\'Helvetica Neue,Helvetica,Arial,sans-serif\';\n"
"    font-weight:296;\n"
"    color:#272727;\n"
"    font-size:9pt;\n"
"}\n"
"\n"
"\n"
"QDockWidget > * {\n"
"    border: 1px solid lightgray;\n"
"    margin: 0px\n"
" }\n"
"\n"
"/* For making nice twistys\n"
" QTreeView::branch:has-siblings:!adjoins-item {\n"
"     border-image: url(images/tree/vline.png) 0;\n"
" }\n"
"\n"
" QTreeView::branch:has-siblings:adjoins-item {\n"
"     border-image: url(images/tree/branch-more.png) 0;\n"
" }\n"
"\n"
" QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"     border-image: url(images/tree/branch-end.png) 0;\n"
" }\n"
"\n"
"\n"
" QTreeView::branch:has-children:!has-siblings:closed,\n"
" QTreeView::branch:closed:has-children:has-siblings {\n"
"         border-image: none;\n"
"         image: url(images/tree/branch-closed.png);\n"
" }\n"
"\n"
" QTreeView::branch:open:has-children:!has-siblings,\n"
" QTreeView::branch:open:has-children:has-siblings  {\n"
"         border-image: none;\n"
"         image: url(images/tree/branch-open.png);\n"
" }\n"
"*/"))
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.centralArea = QtGui.QHBoxLayout()
        self.centralArea.setObjectName(_fromUtf8("centralArea"))
        self.horizontalLayout_3.addLayout(self.centralArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.moduleTreePane = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduleTreePane.sizePolicy().hasHeightForWidth())
        self.moduleTreePane.setSizePolicy(sizePolicy)
        self.moduleTreePane.setStyleSheet(_fromUtf8("font-size:10pt; "))
        self.moduleTreePane.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.moduleTreePane.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.moduleTreePane.setObjectName(_fromUtf8("moduleTreePane"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(200, 250))
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeView = QtGui.QTreeView(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setAcceptDrops(True)
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setDragEnabled(False)
        self.treeView.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.treeView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setIconSize(QtCore.QSize(32, 32))
        self.treeView.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeView.setIndentation(15)
        self.treeView.setAnimated(True)
        self.treeView.setWordWrap(False)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.treeView.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeView)
        self.moduleTreePane.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.moduleTreePane)
        self.panePreview = QtGui.QDockWidget(MainWindow)
        self.panePreview.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.panePreview.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.panePreview.setObjectName(_fromUtf8("panePreview"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.Previewer = QtWebKit.QWebView(self.dockWidgetContents_2)
        self.Previewer.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.Previewer.setObjectName(_fromUtf8("Previewer"))
        self.gridLayout.addWidget(self.Previewer, 2, 0, 1, 2)
        self.line = QtGui.QFrame(self.dockWidgetContents_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.PreviewRefresh = QtGui.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviewRefresh.sizePolicy().hasHeightForWidth())
        self.PreviewRefresh.setSizePolicy(sizePolicy)
        self.PreviewRefresh.setMinimumSize(QtCore.QSize(32, 32))
        self.PreviewRefresh.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica Neue,Helvetica,Arial,sans-serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(37)
        self.PreviewRefresh.setFont(font)
        self.PreviewRefresh.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/view-refresh-4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PreviewRefresh.setIcon(icon1)
        self.PreviewRefresh.setObjectName(_fromUtf8("PreviewRefresh"))
        self.gridLayout.addWidget(self.PreviewRefresh, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.panePreview.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.panePreview)
        self.paneFlowchart = QtGui.QDockWidget(MainWindow)
        self.paneFlowchart.setEnabled(True)
        self.paneFlowchart.setStyleSheet(_fromUtf8("font-size:10pt;\n"
""))
        self.paneFlowchart.setFloating(False)
        self.paneFlowchart.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.paneFlowchart.setObjectName(_fromUtf8("paneFlowchart"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.copyImage = QtGui.QPushButton(self.dockWidgetContents_3)
        self.copyImage.setMinimumSize(QtCore.QSize(0, 0))
        self.copyImage.setMaximumSize(QtCore.QSize(80, 16777215))
        self.copyImage.setObjectName(_fromUtf8("copyImage"))
        self.gridLayout_3.addWidget(self.copyImage, 1, 1, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 383, 69))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.flowchart = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.flowchart.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.flowchart.setText(_fromUtf8(""))
        self.flowchart.setObjectName(_fromUtf8("flowchart"))
        self.verticalLayout_3.addWidget(self.flowchart)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 3)
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 1, 2, 1, 1)
        self.scrollArea_2 = QtGui.QScrollArea(self.dockWidgetContents_3)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.scrollArea_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 366, 108))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.scrollArea_2, 2, 0, 1, 3)
        self.paneFlowchart.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.paneFlowchart)
        self.dataElementDock = QtGui.QDockWidget(MainWindow)
        self.dataElementDock.setStyleSheet(_fromUtf8("font-size:10pt; "))
        self.dataElementDock.setObjectName(_fromUtf8("dataElementDock"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.clusterList = QtGui.QComboBox(self.dockWidgetContents_4)
        self.clusterList.setObjectName(_fromUtf8("clusterList"))
        self.gridLayout_2.addWidget(self.clusterList, 0, 0, 1, 1)
        self.addCluster = QtGui.QPushButton(self.dockWidgetContents_4)
        self.addCluster.setMinimumSize(QtCore.QSize(20, 20))
        self.addCluster.setMaximumSize(QtCore.QSize(20, 20))
        self.addCluster.setObjectName(_fromUtf8("addCluster"))
        self.gridLayout_2.addWidget(self.addCluster, 0, 2, 1, 1)
        self.DataElementList = QtGui.QListView(self.dockWidgetContents_4)
        self.DataElementList.setObjectName(_fromUtf8("DataElementList"))
        self.gridLayout_2.addWidget(self.DataElementList, 1, 0, 1, 3)
        self.removeCluster = QtGui.QPushButton(self.dockWidgetContents_4)
        self.removeCluster.setMinimumSize(QtCore.QSize(20, 20))
        self.removeCluster.setMaximumSize(QtCore.QSize(20, 20))
        self.removeCluster.setObjectName(_fromUtf8("removeCluster"))
        self.gridLayout_2.addWidget(self.removeCluster, 0, 1, 1, 1)
        self.dataElementDock.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dataElementDock)
        self.toolbarFile = QtGui.QToolBar(MainWindow)
        self.toolbarFile.setObjectName(_fromUtf8("toolbarFile"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbarFile)
        self.paneComponents = QtGui.QDockWidget(MainWindow)
        self.paneComponents.setObjectName(_fromUtf8("paneComponents"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.dockWidgetContents_5)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.newItemsList = QtGui.QListView(self.dockWidgetContents_5)
        self.newItemsList.setAcceptDrops(True)
        self.newItemsList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.newItemsList.setDragEnabled(True)
        self.newItemsList.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.newItemsList.setAlternatingRowColors(True)
        self.newItemsList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.newItemsList.setObjectName(_fromUtf8("newItemsList"))
        self.verticalLayout_4.addWidget(self.newItemsList)
        self.paneComponents.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.paneComponents)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 911, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuImport = QtGui.QMenu(self.menuFile)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSettings = QtGui.QMenu(self.menuBar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuTogglePanes = QtGui.QMenu(self.menuSettings)
        self.menuTogglePanes.setObjectName(_fromUtf8("menuTogglePanes"))
        self.menuToggleToolbars = QtGui.QMenu(self.menuSettings)
        self.menuToggleToolbars.setObjectName(_fromUtf8("menuToggleToolbars"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolbarPreviewOptions = QtGui.QToolBar(MainWindow)
        self.toolbarPreviewOptions.setIconSize(QtCore.QSize(24, 24))
        self.toolbarPreviewOptions.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolbarPreviewOptions.setObjectName(_fromUtf8("toolbarPreviewOptions"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbarPreviewOptions)
        self.toolbarRichText = QtGui.QToolBar(MainWindow)
        self.toolbarRichText.setObjectName(_fromUtf8("toolbarRichText"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbarRichText)
        self.toolbarMultilingual = QtGui.QToolBar(MainWindow)
        self.toolbarMultilingual.setObjectName(_fromUtf8("toolbarMultilingual"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbarMultilingual)
        self.actionNewModule = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/document-new-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewModule.setIcon(icon2)
        self.actionNewModule.setObjectName(_fromUtf8("actionNewModule"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/document-open-5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon3)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/document-save-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSaveAs = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/document-save-as-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon5)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionRefeshPreviewers = QtGui.QAction(MainWindow)
        self.actionRefeshPreviewers.setIcon(icon1)
        self.actionRefeshPreviewers.setObjectName(_fromUtf8("actionRefeshPreviewers"))
        self.actionBlame = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Canard_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBlame.setIcon(icon6)
        self.actionBlame.setObjectName(_fromUtf8("actionBlame"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionRecent_Files = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/document-open-recent-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecent_Files.setIcon(icon7)
        self.actionRecent_Files.setObjectName(_fromUtf8("actionRecent_Files"))
        self.actionRefreshImport = QtGui.QAction(MainWindow)
        self.actionRefreshImport.setObjectName(_fromUtf8("actionRefreshImport"))
        self.actionRefreshExport = QtGui.QAction(MainWindow)
        self.actionRefreshExport.setObjectName(_fromUtf8("actionRefreshExport"))
        self.actionPlugins = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/network-connect-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlugins.setIcon(icon8)
        self.actionPlugins.setObjectName(_fromUtf8("actionPlugins"))
        self.actionAutoRefreshFlowchart = QtGui.QAction(MainWindow)
        self.actionAutoRefreshFlowchart.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/view-sidetree-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoRefreshFlowchart.setIcon(icon9)
        self.actionAutoRefreshFlowchart.setObjectName(_fromUtf8("actionAutoRefreshFlowchart"))
        self.actionAutoRefreshPreviewer = QtGui.QAction(MainWindow)
        self.actionAutoRefreshPreviewer.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/view-right-new-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoRefreshPreviewer.setIcon(icon10)
        self.actionAutoRefreshPreviewer.setObjectName(_fromUtf8("actionAutoRefreshPreviewer"))
        self.actionInsertWordsub = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/insert-text-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertWordsub.setIcon(icon11)
        self.actionInsertWordsub.setObjectName(_fromUtf8("actionInsertWordsub"))
        self.actionCreateNewWordsub = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/insert-text-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreateNewWordsub.setIcon(icon12)
        self.actionCreateNewWordsub.setObjectName(_fromUtf8("actionCreateNewWordsub"))
        self.actionAddLanguageGlobally = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/applications-development-translation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddLanguageGlobally.setIcon(icon13)
        self.actionAddLanguageGlobally.setObjectName(_fromUtf8("actionAddLanguageGlobally"))
        self.actionShowPreferences = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/preferences-system-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowPreferences.setIcon(icon14)
        self.actionShowPreferences.setObjectName(_fromUtf8("actionShowPreferences"))
        self.actionFileABug = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/file/actions/tools-report-bug.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileABug.setIcon(icon15)
        self.actionFileABug.setObjectName(_fromUtf8("actionFileABug"))
        self.actionNewDerivedDataItem = QtGui.QAction(MainWindow)
        self.actionNewDerivedDataItem.setObjectName(_fromUtf8("actionNewDerivedDataItem"))
        self.actionNewCalculatedDataItem = QtGui.QAction(MainWindow)
        self.actionNewCalculatedDataItem.setObjectName(_fromUtf8("actionNewCalculatedDataItem"))
        self.toolbarFile.addAction(self.actionNewModule)
        self.toolbarFile.addAction(self.actionOpen)
        self.toolbarFile.addAction(self.actionSave)
        self.toolbarFile.addAction(self.actionSaveAs)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionRefreshImport)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionRefreshExport)
        self.menuFile.addAction(self.actionNewModule)
        self.menuFile.addAction(self.actionRecent_Files)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionFileABug)
        self.menuHelp.addAction(self.actionBlame)
        self.menuSettings.addAction(self.actionAddLanguageGlobally)
        self.menuSettings.addAction(self.actionShowPreferences)
        self.menuSettings.addAction(self.menuTogglePanes.menuAction())
        self.menuSettings.addAction(self.menuToggleToolbars.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolbarPreviewOptions.addAction(self.actionRefeshPreviewers)
        self.toolbarPreviewOptions.addAction(self.actionAutoRefreshFlowchart)
        self.toolbarPreviewOptions.addAction(self.actionAutoRefreshPreviewer)
        self.toolbarRichText.addAction(self.actionInsertWordsub)
        self.toolbarMultilingual.addAction(self.actionAddLanguageGlobally)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.scrollArea_2.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Canard Question Module Editor - ", None, QtGui.QApplication.UnicodeUTF8))
        self.moduleTreePane.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Module Components", None, QtGui.QApplication.UnicodeUTF8))
        self.panePreview.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Live preview", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Blaise", None, QtGui.QApplication.UnicodeUTF8))
        self.PreviewRefresh.setToolTip(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.paneFlowchart.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Flowchart", None, QtGui.QApplication.UnicodeUTF8))
        self.copyImage.setText(QtGui.QApplication.translate("MainWindow", "Copy Image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600;\">Ovals</span><span style=\" font-size:8pt;\"> - Questions or statements</span><br/><span style=\" font-size:8pt; font-weight:600;\">Diamonds</span><span style=\" font-size:8pt;\"> - Sequence guides<br/></span><span style=\" font-size:8pt; font-weight:600;\">Octagons</span><span style=\" font-size:8pt;\"> - Module breakpoints</span><br/><span style=\" font-size:8pt; font-weight:600;\">Black Lines</span><span style=\" font-size:8pt;\"> - Paths between questions, sequence guides, etc...</span><br/><span style=\" font-size:8pt; font-weight:600; color:#818181;\">Gray</span><span style=\" font-size:8pt; font-weight:600;\"> lines</span><span style=\" font-size:8pt;\"> - Where questions help split populations in sequence guides <br/></span><span style=\" font-size:8pt; font-weight:600; color:#aa0000;\">Red</span><span style=\" font-size:8pt; font-weight:600;\"> lines</span><span style=\" font-size:8pt;\"> - Break paths that immediately exit a module </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.dataElementDock.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Data Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.addCluster.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removeCluster.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarFile.setWindowTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.paneComponents.setWindowTitle(QtGui.QApplication.translate("MainWindow", "New Components", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Drag from the list below in to the <span style=\" font-weight:600;\">Flow Logic</span> to add new parts to a question module.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImport.setTitle(QtGui.QApplication.translate("MainWindow", "&Import...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("MainWindow", "&Export...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTogglePanes.setTitle(QtGui.QApplication.translate("MainWindow", "Show / hide panes...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToggleToolbars.setTitle(QtGui.QApplication.translate("MainWindow", "Show / hide toolbars...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarPreviewOptions.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarRichText.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Rich Text", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbarMultilingual.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Multilingual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewModule.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewModule.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save &As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefeshPreviewers.setText(QtGui.QApplication.translate("MainWindow", "Refresh Previewers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefeshPreviewers.setToolTip(QtGui.QApplication.translate("MainWindow", "Refesh Preview and Flowchart viewers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefeshPreviewers.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlame.setText(QtGui.QApplication.translate("MainWindow", "&About Canard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlame.setToolTip(QtGui.QApplication.translate("MainWindow", "About Canard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent_Files.setText(QtGui.QApplication.translate("MainWindow", "&Recent Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefreshImport.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefreshExport.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlugins.setText(QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlugins.setToolTip(QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoRefreshFlowchart.setText(QtGui.QApplication.translate("MainWindow", "Auto refresh flowchart", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoRefreshFlowchart.setToolTip(QtGui.QApplication.translate("MainWindow", "Auto refresh flowchart", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoRefreshPreviewer.setText(QtGui.QApplication.translate("MainWindow", "Auto refresh previewer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutoRefreshPreviewer.setToolTip(QtGui.QApplication.translate("MainWindow", "Auto refresh previewer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertWordsub.setText(QtGui.QApplication.translate("MainWindow", "Insert Wordsub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsertWordsub.setToolTip(QtGui.QApplication.translate("MainWindow", "Insert a \"Word subtitution\" into the current rich text field", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateNewWordsub.setText(QtGui.QApplication.translate("MainWindow", "Create new Wordsub", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateNewWordsub.setToolTip(QtGui.QApplication.translate("MainWindow", "Create a new \"Word subtitution\"", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateNewWordsub.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddLanguageGlobally.setText(QtGui.QApplication.translate("MainWindow", "Add Language &Globally", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddLanguageGlobally.setToolTip(QtGui.QApplication.translate("MainWindow", "Add a new language set to every text component in a survey ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddLanguageGlobally.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPreferences.setText(QtGui.QApplication.translate("MainWindow", "&Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPreferences.setToolTip(QtGui.QApplication.translate("MainWindow", "Edit Canard user preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileABug.setText(QtGui.QApplication.translate("MainWindow", "File a bug...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewDerivedDataItem.setText(QtGui.QApplication.translate("MainWindow", "New Derived Data Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewCalculatedDataItem.setText(QtGui.QApplication.translate("MainWindow", "New Calculated Data Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewCalculatedDataItem.setToolTip(QtGui.QApplication.translate("MainWindow", "New Calculated Data Item", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import canard_rc
